const schemes=[{id:"pmkisan",title:"PM-KISAN",tag:"Central scheme",summary:"Income support information for eligible landholding farmer families.",audience:"Eligible landholding farmer families",docs:["Identity details","Bank account information","Landholding records"],source:"PM-KISAN official portal",url:"https://pmkisan.gov.in/"},{id:"pmfby",title:"PMFBY",tag:"Crop insurance",summary:"Guidance on crop insurance rules, eligibility and enrolment.",audience:"Farmers covered under notified crops and applicable conditions",docs:["Identity details","Land or cultivation records","Bank account information"],source:"PMFBY official portal",url:"https://pmfby.gov.in/"},{id:"kcc",title:"Kisan Credit Card",tag:"Credit support",summary:"Guidance on agricultural credit access, documents and the appropriate lender.",audience:"Eligible farmers and agricultural borrowers",docs:["Identity/address proof","Land or cultivation documents","Lender documents"],source:"Official banking and government guidance",url:"#"}];
let draft=JSON.parse(localStorage.getItem("shaya_draft")||"null");
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",""":"&quot;","'":"&#039;"}[c]));
const root=()=>document.getElementById("modalRoot");
function go(id){document.getElementById(id)?.scrollIntoView({behavior:"smooth",block:"start"});}
function modal(html){root().innerHTML='<div class="modal" onclick="if(event.target===this)this.remove()"><div class="panel">'+html+"</div></div>";}
function openHelp(){modal('<button class="modal-close" onclick="this.closest(\'.modal\').remove()">Close</button><span class="badge">HELP DESK</span><h2>Tell us what happened.</h2><p>Start with the situation in your own words. You do not need to know the department first.</p><div class="field"><label>What do you need help with?</label><textarea id="helpText" placeholder="Example: I applied for crop insurance but I cannot see the status."></textarea></div><div class="panel-actions"><button class="cta" onclick="routeHelp()">Find a route →</button><button class="ghost" onclick="grievance();this.closest(\'.modal\').remove()">Raise a grievance</button></div><div id="helpAnswer"></div>');}
function routeHelp(){const q=(document.getElementById("helpText")?.value||"").toLowerCase();let html;if(/crop|insurance|pmfby/.test(q)){html='<div class="assist-answer"><strong>Suggested route: PMFBY</strong><p>Open the crop-insurance guidance, then use the official route for current rules or status information.</p><div class="panel-actions"><button class="cta" onclick="showScheme(\'pmfby\')">View PMFBY →</button><button class="ghost" onclick="go(\'grievance\');document.querySelector(\'.modal\')?.remove()">Prepare grievance</button></div></div>';}else if(/pacs|cooperative|society/.test(q)){html='<div class="assist-answer"><strong>Suggested route: Cooperative desk</strong><p>Start with the cooperative section and move toward the relevant local service route.</p></div>';}else{html='<div class="assist-answer"><strong>Use the words you already use.</strong><p>Try a scheme, document, PACS, application, status, or problem.</p></div>';}document.getElementById("helpAnswer").innerHTML=html;}
function searchSchemes(){const q=document.getElementById("schemeSearch").value.toLowerCase().trim();const list=schemes.filter(s=>!q||[s.title,s.tag,s.summary,s.audience].join(" ").toLowerCase().includes(q));document.getElementById("schemeResults").innerHTML=list.map(s=>'<article class="result-card"><span class="pill">'+esc(s.tag)+'</span><h3>'+esc(s.title)+'</h3><p>'+esc(s.summary)+'</p><div class="panel-actions"><button class="cta" onclick="showScheme(\''+s.id+'\')">View details →</button><a class="ghost" target="_blank" rel="noreferrer" href="'+s.url+'">Official source</a></div></article>').join("")||'<div class="result-card"><strong>No matching demo route.</strong><p>Try another scheme or service term.</p></div>';}
function showScheme(id){const s=schemes.find(x=>x.id===id);modal('<button class="modal-close" onclick="this.closest(\'.modal\').remove()">Close</button><span class="pill">'+esc(s.tag)+'</span><h2>'+esc(s.title)+'</h2><p>'+esc(s.summary)+'</p><h3>Who it is for</h3><p>'+esc(s.audience)+'</p><h3>Keep ready</h3><ul>'+s.docs.map(d=>"<li>"+esc(d)+"</li>").join("")+'</ul><div class="assist-answer"><strong>Source: '+esc(s.source)+'</strong><p>Verify current eligibility and procedure on the official source before taking action.</p></div><div class="panel-actions"><a class="cta" target="_blank" rel="noreferrer" href="'+s.url+'">Open official source →</a></div>');}
function grievance(){const d=draft||{category:"Scheme / service",title:"",description:""};modal('<button class="modal-close" onclick="this.closest(\'.modal\').remove()">Close</button><span class="badge">GRIEVANCE DRAFT</span><h2>Prepare the message.</h2><p>Nothing is submitted from this prototype. Save and review a local draft first.</p><div class="field"><label>Issue category</label><select id="gc">'+["Scheme / service","PACS / cooperative","Document / application","Other"].map(x=>"<option "+(d.category===x?"selected":"")+">"+x+"</option>").join("")+'</select></div><div class="field"><label>Short title</label><input id="gt" value="'+esc(d.title)+'" placeholder="Application status is not updated"></div><div class="field"><label>What happened?</label><textarea id="gd" placeholder="Explain what happened, where, when, and what help you need.">'+esc(d.description)+'</textarea></div><div class="panel-actions"><button class="cta" onclick="saveDraft()">Save local draft →</button><button class="ghost" onclick="previewDraft()">Review</button></div><div id="draftMsg"></div>');go("grievance");}
function saveDraft(){draft={category:document.getElementById("gc").value,title:document.getElementById("gt").value.trim(),description:document.getElementById("gd").value.trim()};localStorage.setItem("shaya_draft",JSON.stringify(draft));updatePreview();const m=document.getElementById("draftMsg");if(m)m.innerHTML='<div class="assist-answer">Saved in this browser. A real complaint is not submitted by this prototype.</div>';}
function updatePreview(){if(draft?.title)document.getElementById("draftPreviewTitle").textContent=draft.title;if(draft?.description)document.getElementById("draftPreviewText").textContent=draft.description;}
function previewDraft(){const title=document.getElementById("gt").value.trim()||"Untitled request",desc=document.getElementById("gd").value.trim()||"No description yet";modal('<button class="modal-close" onclick="this.closest(\'.modal\').remove()">Close</button><span class="badge">PREVIEW</span><h2>'+esc(title)+'</h2><p>'+esc(document.getElementById("gc").value)+'</p><div class="assist-answer">'+esc(desc)+'</div><div class="panel-actions"><button class="cta" onclick="saveDraft();this.closest(\'.modal\').remove()">Save draft →</button></div>');}
document.addEventListener("keydown",e=>{if(e.key==="Escape")document.querySelector(".modal")?.remove()});
document.addEventListener("DOMContentLoaded",()=>{searchSchemes();updatePreview();const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add("in")}),{threshold:.12});document.querySelectorAll(".reveal").forEach(el=>io.observe(el));});
window.addEventListener("scroll",()=>{document.querySelectorAll(".hero-object .orb").forEach((o,i)=>o.style.transform="translateY("+(window.scrollY*(i+1)*.025)+"px)")});