import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';

void main()=>runApp(const ShayaApp());

class ShayaApp extends StatelessWidget{
 const ShayaApp({super.key});
 @override Widget build(BuildContext context)=>MaterialApp(debugShowCheckedModeBanner:false,title:'SHAYA',theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:const Color(0xFFF1EEE5),colorScheme:ColorScheme.fromSeed(seedColor:const Color(0xFFD8FF4A),brightness:Brightness.light),textTheme:GoogleFonts.dmSansTextTheme()),home:const Home());
}

class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{
 int tab=0;
 final schemes=[('PM-KISAN','Income support','Eligibility, documents and official route.'),('PMFBY','Crop insurance','Crop insurance guidance and procedure.'),('Kisan Credit Card','Credit support','Documents and agricultural credit route.')];
 @override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:CustomScrollView(slivers:[
 SliverAppBar(backgroundColor:const Color(0xFFF1EEE5),surfaceTintColor:Colors.transparent,pinned:true,title:Row(children:[Container(width:36,height:36,alignment:Alignment.center,decoration:BoxDecoration(color:const Color(0xFF11140F),borderRadius:BorderRadius.circular(10)),child:const Text('S',style:TextStyle(color:Color(0xFFD8FF4A),fontWeight:FontWeight.bold))),const SizedBox(width:9),const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('SHAYA',style:TextStyle(fontWeight:FontWeight.w800,fontSize:13)),Text('COOPERATIVE ASSISTANCE',style:TextStyle(fontSize:7,color:Colors.grey,letterSpacing:1.3))])]),actions:[IconButton(onPressed:()=>_help(context),icon:const Icon(Icons.north_east))]),
 SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(22,42,22,30),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[
 const Text('A CIVIC SERVICE PROTOTYPE',style:TextStyle(fontSize:10,letterSpacing:1.5,color:Colors.grey,fontWeight:FontWeight.w600)),
 const SizedBox(height:20),Text('Cooperative help,',style:TextStyle(fontSize:48,height:.9,fontWeight:FontWeight.w800,letterSpacing:-2)),Text('without the maze.',style:GoogleFonts.playfairDisplay(fontSize:43,height:1.0,fontStyle:FontStyle.italic,color:const Color(0xFF858277))),
 const SizedBox(height:20),const Text('Find schemes, understand cooperative services and prepare the next step without needing to know the department first.',style:TextStyle(color:Color(0xFF6F7168),height:1.6,fontSize:14)),
 const SizedBox(height:24),FilledButton.icon(onPressed:()=>_help(context),icon:const Icon(Icons.arrow_forward,size:17),label:const Text('Tell us what happened'),style:FilledButton.styleFrom(backgroundColor:const Color(0xFF11140F),foregroundColor:Colors.white,padding:const EdgeInsets.symmetric(horizontal:18,vertical:15),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(13)))),
 const SizedBox(height:38),Container(height:290,width:double.infinity,decoration:BoxDecoration(color:const Color(0xFF171B14),borderRadius:BorderRadius.circular(28)),child:Stack(children:[Positioned(right:-30,top:-30,child:Container(width:180,height:180,decoration:const BoxDecoration(color:Color(0xFFD8FF4A),shape:BoxShape.circle))),Positioned(left:22,top:22,child:const Text('SHAYA     01',style:TextStyle(color:Color(0xFFB1B5A5),fontSize:9,letterSpacing:2))),Positioned(left:25,bottom:45,child:Text('One place.\nClear next step.',style:TextStyle(color:Colors.white,fontSize:35,height:.95,fontWeight:FontWeight.w600,letterSpacing:-1))),Positioned(left:25,bottom:23,child:Text('SCHEME        HELP        GRIEVANCE',style:TextStyle(color:Color(0xFF9BA08F),fontSize:8,letterSpacing:1.2))) ])),
 ]))),
 SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(22,35,22,12),child:Text('START WITH THE THING YOU NEED',style:TextStyle(fontSize:10,letterSpacing:1.5,color:Colors.grey,fontWeight:FontWeight.w700)))),
 SliverPadding(padding:const EdgeInsets.symmetric(horizontal:22),sliver:SliverList(delegate:SliverChildListDelegate([
 _card(context,Icons.landscape,'Find a scheme','Eligibility, documents and where to continue.',0),
 _card(context,Icons.chat_bubble_outline,'Ask for help','Explain the situation in normal words.',1),
 _card(context,Icons.description_outlined,'Prepare a grievance','Turn an issue into a reviewable draft.',2),
 _card(context,Icons.account_balance_outlined,'Cooperative services','Understand what to ask your PACS about.',3),
 ]))),
 SliverToBoxAdapter(child:Padding(padding:const EdgeInsets.fromLTRB(22,40,22,15),child:Text('SCHEME NAVIGATOR',style:TextStyle(fontSize:10,letterSpacing:1.5,color:Colors.grey,fontWeight:FontWeight.w700)))),
 SliverPadding(padding:const EdgeInsets.symmetric(horizontal:22),sliver:SliverList(delegate:SliverChildBuilderDelegate((c,i)=>_scheme(schemes[i]),childCount:schemes.length))),
 const SliverToBoxAdapter(child:SizedBox(height:50))
 ])));
 Widget _card(BuildContext c,IconData icon,String title,String body,int i)=>Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(19),decoration:BoxDecoration(color:i==2?const Color(0xFFEFD9D0):i==3?const Color(0xFFDCE9DF):const Color(0xFFF8F5ED),border:Border.all(color:const Color(0xFFD0CDC1)),borderRadius:BorderRadius.circular(20)),child:InkWell(onTap:()=>i==1?_help(c):null,child:Row(children:[Icon(icon,size:23),const SizedBox(width:15),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(title,style:const TextStyle(fontWeight:FontWeight.w700,fontSize:17)),const SizedBox(height:5),Text(body,style:const TextStyle(color:Color(0xFF77796D),fontSize:11,height:1.5))])),const Icon(Icons.arrow_forward,size:17)])));
 Widget _scheme((String,String,String) s)=>Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(19),decoration:BoxDecoration(color:const Color(0xFF171B14),borderRadius:BorderRadius.circular(19)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(s.$2.toUpperCase(),style:const TextStyle(color:Color(0xFFD8FF4A),fontSize:9,letterSpacing:1.2)),const SizedBox(height:28),Text(s.$1,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w700,fontSize:21)),const SizedBox(height:8),Text(s.$3,style:const TextStyle(color:Color(0xFFA8AA9D),fontSize:11,height:1.5)),const SizedBox(height:16),const Text('View official route  ↗',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w600,fontSize:10))]));
 void _help(BuildContext context){final controller=TextEditingController();showModalBottomSheet(context:context,isScrollControlled:true,backgroundColor:const Color(0xFFF1EEE5),shape:const RoundedRectangleBorder(borderRadius:BorderRadius.vertical(top:Radius.circular(28))),builder:(c)=>Padding(padding:EdgeInsets.fromLTRB(22,25,22,MediaQuery.of(c).viewInsets.bottom+25),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('HELP DESK',style:TextStyle(fontSize:9,letterSpacing:1.5,color:Colors.grey)),const SizedBox(height:15),const Text('Tell us what happened.',style:TextStyle(fontSize:32,fontWeight:FontWeight.w800,letterSpacing:-1)),const SizedBox(height:8),const Text('You do not need to know the scheme name first.',style:TextStyle(color:Colors.grey,fontSize:12)),const SizedBox(height:16),TextField(controller:controller,maxLines:5,decoration:InputDecoration(hintText:'Example: I applied for crop insurance but cannot see the status.',filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(14),borderSide:BorderSide.none))),const SizedBox(height:12),FilledButton.icon(onPressed:(){final q=controller.text.toLowerCase();final msg=q.contains('crop')||q.contains('insurance')?'Suggested route: PMFBY. Verify the current procedure on the official source.':q.contains('pacs')||q.contains('cooperative')?'Suggested route: Cooperative services.':'Try naming a scheme, document, PACS, application, status, or problem.';showDialog(context:context,builder:(_)=>AlertDialog(title:const Text('Suggested next step'),content:Text(msg),actions:[TextButton(onPressed:()=>Navigator.pop(context),child:const Text('Close'))]));},icon:const Icon(Icons.arrow_forward),label:const Text('Find a route'),style:FilledButton.styleFrom(backgroundColor:const Color(0xFF11140F),foregroundColor:Colors.white,minimumSize:const Size(double.infinity,50)))]));}
}
